### ISSUE TITLE
npm run dev --> SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by GrippenDynamik** [guansss/webpack-monkey#2]
I've followed the steps in [1. Set up the project](https://www.npmjs.com/package/webpack-monkey#1-set-up-the-project), and everything worked fine.
But executing `npm run dev` causes this error:
```
[webpack-cli] Failed to load '/home/username/webpack-monkey-test/webpack.config.js' config
[webpack-cli] /home/username/webpack-monkey-test/node_modules/webpack-monkey/lib/node/monkey.js:10
    const userDefinedRuntimeChunk = config?.optimization?.runtimeChunk;
                                           ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/username/webpack-monkey-test/node_modules/webpack-monkey/lib/index.js:18:14)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

What other information do you need to debug the error?

**Comment by guansss** [comment]
It looks like your environment does not recognize the `?.` operator, which [requires Node.js > 14](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining#browser_compatibility). Please check if your Node.js version meets the requirement.

**Comment by GrippenDynamik** [comment]
Sorry about the late reply.

You're right, my Node.js version was very outdated.
Linux Mint 21.2 still offers Node.js 12.22.9 via the package manager.
Upgrading Node.js to 21.5.0 with NVM fixed the problem, and now everything works perfectly!

One small thing I noticed:
When I follow your [quick start](url=https://github.com/guansss/webpack-monkey#quick-start) guide, Tampermonkey 5.0.0 on Firefox 121.0 complains that `match: ["*://example.com"]` isn't a valid match pattern, because there's no path.
Changing it to `match: ["*://example.com/"]` fixed the problem.

**Comment by guansss** [comment]
Fixed the docs, thank you for reporting!
