### ISSUE TITLE
"match" in meta file didn't support port

### ISSUE THREAD

**Issue by Mr-Python-in-China** [guansss/webpack-monkey#4]
I tried:
```json
{
  "name":"test",
  "match": ["*://localhost:54220/"]
}
```
And got an error in console:
```
Error matching script "main": TypeError: Invalid pattern: *://localhost:54220/
    at urlMatch (utils.js:23:15)
    at eval (client.js:27:60)
    at Array.some (<anonymous>)
    at matchUserscript (client.js:27:21)
    at Array.filter (<anonymous>)
    at Proxy.eval (client.js:22:13)
    at ./node_modules/.store/webpack-monkey-virtual-b8d7e0e2c3/package/lib/client/client.js (eval at onload (localhost/:78:13), <anonymous>:455:1)
    at __webpack_require__ (eval at onload (localhost/:78:13), <anonymous>:36:32)
    at __webpack_exec__ (eval at onload (localhost/:78:13), <anonymous>:633:48)
    at eval (eval at onload (localhost/:78:13), <anonymous>:634:471)
```

In `utils.js`
```js
function urlMatch(pattern, url) {
    const matcher = (0, browser_extension_url_match_1.matchPattern)(pattern);
    if (!matcher.valid) {
        throw new TypeError("Invalid pattern: " + pattern);
    }
    return matcher.match(url);
}
```
`matcher.error` is `Error: Host "localhost:54220" cannot include a port number. All ports are matched by default.`.

Then I tried `"match": ["*://localhost/"]` and visited `localhost:54220`, but matcher.match(url) return `false`, so my script didn't work.

**Comment by Mr-Python-in-China** [comment]
browser-extension-url-match works good on version 1.0.0

You may need to update the dependence?

**Comment by guansss** [comment]
Did browser-extension-url-match 1.0.0 really work for you? I tried upgrading it to 1.0.0 and even 1.2.0, and it still threw that error.

The matching algorithm it simulates also does not support port matching, so it seems to work as intended.

https://developer.chrome.com/docs/extensions/mv3/match_patterns/
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns

**Comment by Mr-Python-in-China** [comment]
![image](https://github.com/guansss/webpack-monkey/assets/89737170/951e4607-03f2-4624-8b0c-744d517ef830)
![image](https://github.com/guansss/webpack-monkey/assets/89737170/f568928d-2109-4411-a850-98bf9b07aead)

I means, the url "http://localhost/" didn't match "http://localhost:9000/". It's not same as tampermonkey. New version seems work well

**Comment by guansss** [comment]
Ah, I see, you are right. I'll update the version later, thanks for reporting!
